app:
  name: "Teraryum User Service"  

quarkus:
  datasource:
    db-kind: mysql
    username: u670356437_teraryum
    password: epkh4Q*d2nHb618u
    jdbc: 
      ~: false
    reactive:
      url: vertx-reactive:mysql://sql418.main-hosting.eu:3306/u670356437_tera_users
      max-size: 20

  # drop and create the database at startup (use `update` to only update the schema)
  hibernate-orm:
    database:
      generation: 
        ~: drop-and-create
    log:
      sql: true
    sql-load-script: import.sql
  
  smallrye-openapi:
    path: /cpanel/openapi

  swagger-ui:
      always-include: true
      path: /cpanel/swagger