---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 15a31d079d4e5b2672d56de2dbd7695f1c5b7d11
    app.quarkus.io/build-timestamp: 2021-12-29 - 17:32:04 +0000
  labels:
    app.kubernetes.io/name: ws-rest-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: ws-rest-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ws-rest-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP