apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: b4dbd5b9239b57fc4200a7952f90a3fe327e3282
    app.quarkus.io/build-timestamp: 2021-12-29 - 21:55:14 +0000
    dev.okteto.com/auto-ingress: "true"
  labels:
    app.kubernetes.io/name: ws-rest-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: ws-rest-api
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ws-rest-api
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
